Ini, TOML
# .streamlit/secrets.toml

SUPABASE_URL = "https://dnurqyjzgrmizvbgibzn.supabase.co/rest/v1/"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRudXJxeWp6Z3JtaXp2YmdpYnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4NzA2MzQsImV4cCI6MjEwMjQ0NjYzNH0.PqwVRgBSW_DJzM9fcpuDb17qixLPi41evuh5675s2AA"
